debug ip

diff --git a/.github/workflows/datamart.yml b/.github/workflows/datamart.yml
--- a/.github/workflows/datamart.yml
+++ b/.github/workflows/datamart.yml
@@ -42,8 +42,13 @@ jobs:
     # 6. Extract the IP of Hazelcast instance
     - name: Get Hazelcast IP
       run: |
+        HAZELCAST_IP=$(terraform output -raw hazelcast_public_ip 2>/dev/null | tr -d '\r' || echo "ERROR")
+        echo "HAZELCAST_IP=${HAZELCAST_IP}" >> $GITHUB_ENV
+
+    - name: Debug Hazelcast IP
+      run: |
         HAZELCAST_IP=$(terraform output -raw hazelcast_public_ip 2>/dev/null || echo "ERROR")
-        echo "HAZELCAST_IP=$HAZELCAST_IP" >> $GITHUB_ENV
+        echo "HAZELCAST_IP=${HAZELCAST_IP}"
 
 
     # 7. Install Java and Maven
